### ISSUE TITLE
Cannot read property 'transports' of undefined

### ISSUE THREAD

**Issue by JonnyBGod** [mean-expert-official/loopback-component-realtime#27]
Getting following error after updating to 1.0.0-rc-5

```
/node_modules/@mean-expert/loopback-component-realtime/dist/drivers/io.driver.js:19
        this.server = server(options.server, { transports: options.driver.options.transports });
                                                                                 ^

TypeError: Cannot read property 'transports' of undefined
    at IODriver.connect (/Users/joaoribeiro/Documents/Projects/seeds/api-seed/node_modules/@mean-expert/loopback-component-realtime/dist/drivers/io.driver.js:19:82)
    at Function.RealTime.connect (/Users/joaoribeiro/Documents/Projects/seeds/api-seed/node_modules/@mean-expert/loopback-component-realtime/dist/index.js:35:25)
    at EventEmitter.<anonymous> (/Users/joaoribeiro/Documents/Projects/seeds/api-seed/node_modules/@mean-expert/loopback-component-realtime/dist/index.js:28:26)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Server.<anonymous> (/Users/joaoribeiro/Documents/Projects/seeds/api-seed/server/server.js:66:9)
    at Server.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1288:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```

current config:

```
  "@mean-expert/loopback-component-realtime": {
    "debug": false,
    "auth": true,
    "driver": {
      "name": "socket.io"
    },
    "modules": [
      "IO",
      "PubSub",
      "FireLoop",
      "WebRTCSignaler"
    ]
  }
```

**Comment by jonathan-casarrubias** [comment]
@JonnyBGod it seems that the Object.assign I use to add your custom settings to the default, removes the default options from the component.

I'll see how to internally fix that, but for now you just need to update your settings as follows:

````json
  "@mean-expert/loopback-component-realtime": {
    "debug": false,
    "auth": true,
    "driver": {
      "name": "socket.io",
      "options": {}
    },
    "modules": [
      "IO",
      "PubSub",
      "FireLoop",
      "WebRTCSignaler"
    ]
  }
}
````

For now by adding an empty options object, the Object.assign won't remove the default settings from the component, so there is no need you pass any options, it is basically to avoid the default options to be removed.

Cheers
Jon

**Comment by JonnyBGod** [comment]
Great thanks, temporary fix works.

Will leave the issue open until it is fully fixed for others reference.
